config/routes.rb
Rails.application.routes.draw do
  root 'stories#index'

  resources :stories do
    resources :nodes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/node.rb
class Node < ActiveRecord::Base


  has_and_belongs_to_many :stories
  validates :sentence, :presence => true

  # def self.get_gifs(search)
  #   api_instance = GiphyClient::DefaultApi.new
  #
  #   api_key = "KJh1iqhdhBGzqwAv3xq8zWkwQjAdfURf"
  #
  #
  #   opts = {
  #       limit: 25, # Integer | The maximum number of records to return.
  #       offset: 0, # Integer | An optional results offset. Defaults to 0.
  #       rating: "g", # String | Filters results by specified rating.
  #       lang: "en", # String | Specify default country for regional content; use a 2-letter ISO 639-1 country code. See list of supported languages <a href = \"../language-support\">here</a>.
  #       fmt: "json" # String | Used to indicate the expected response format. Default is Json.
  #   }
  #
  #   begin
  #     #Search Endpoint
  #     result = api_instance.gifs_search_get(api_key, 'cheeseburgers', opts)
  #     p result
  #   rescue GiphyClient::ApiError => e
  #     puts "Exception when calling DefaultApi->gifs_search_get: #{e}"
  #   end
  # end
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_and_belongs_to_many :nodes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController

  def create
    @story = Story.find(params[:story_id])
    new_node_params = params[:node]
    new_node = Node.create(sentence: new_node_params[:sentence], signature: new_node_params[:signature], gif_url:   new_node_params[:gif_url])
    @story.nodes.push(new_node)
    @gifs = Node.get_gifs("cheeseburgers")
    binding.pry
    redirect_to :controller => 'stories', :action => 'show', :id => @story.id
  end

  def update
    # right now we never get here, moving to stories controller
    @story = Story.find(params[:story_id])
    selected_node = Node.find(params[:id])
    @story.nodes.push(selected_node)
    # @next_nodes = Node.last(2)
    # @previous_nodes = @story.nodes
    redirect_to :controller => 'stories', :action => 'show', :id => @story.id
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all

  end

  def show
    @story = Story.find(params[:id])
    last_node = @story.nodes.last
    unless last_node.nil?
      unless last_node.next_nodes_ids.nil?
        next_ids = last_node.next_nodes_ids.split(',')
        @next_nodes = [(Node.find(next_ids[0])), (Node.find(next_ids[1]))]
      end
    end
  end

  def new

  end

  def create
    story_params = params[:story]
    new_story = Story.create(:title => story_params[:title])
    new_story.nodes.push(Node.first)
    new_story.save
    redirect_to action: "show", id: new_story.id
  end

  def update
    @story = Story.find(params[:id])
    next_nodes_ids = params.dig(:node, :next_nodes_ids)
    selected_sentence = params[:commit]
    selected_node = Node.where(:sentence => selected_sentence)
    @story.nodes.push(selected_node)
    @next_nodes = []
    next_nodes_ids.split(',').each do |id|
      @next_nodes << Node.find(id)
    end
    @previous_nodes = @story.nodes
    redirect_to action: "show", id: @story.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_controller_helper.rb
module NodesControllerHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Giffic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
    <div class="navbar">
      <%= link_to root_path do %>
        <%= image_tag 'giffic-logo.png', class: "nav-logo", alt: 'logo'%>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/nodes/_node_buttons.html.erb
<div class="next-node">
<!--  <h1 class="current-sentence">Once upon a time...</h1>-->
  <div class="row" id="selections">
    <% @next_nodes.each do |node| %>
      <%= form_for node, :url => {:action => :update, params: {story_id: @story.id}} do |f| %>
        <%= f.hidden_field :next_nodes_ids, :value => node.next_nodes_ids %>
        <%= f.submit node.sentence, class: "btn btn-secondary btn-lg node-button" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/nodes/_node_form.html.erb
<div class="card add-passage">
  <div class="card-body">
    <h4>You've reached the end of what's written.</h4>
    <% node = Node.new %>
    <%= form_for node, :url => url_for(:controller => 'nodes', :action => 'create', :story_id => @story.id) do |f| %>
      <%#= f.label :sentence, "Keep the story going:" %>
      <%= f.text_field :sentence, class: "form-control", placeholder: "Add next passage here" %>
      <br>
      <%#= f.label :signature, "Leave your initials:" %>
      <%= f.text_field :signature, class: "form-control", placeholder: "Enter initials here" %>
      <br>
      <%= f.text_field :gif_url, class: "form-control", placeholder: "Enter gif URL here" %>
      <br>
      <%= f.submit "Add to story", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/nodes/index.html.erb
<div class="container welcome-page">
  <br>
  <div class="header">
    <h1>Welcome to GifFic</h1>
    <p>Where <strong>you</strong> write the story.</p>
  </div>
  <div class="card">
    <div class="card-body">
      <div class="welcome-text">
        <p>(Insert welcome text here)<br>
          (more text)
          <br>
          (even more text)
          <br>
          (even MORE text)
        </p>
      </div>
    </div>
  </div>
  <button class="btn btn-danger btn-lg begin-butt">
    <%= link_to node_path(@next_nodes[0]) do %>
      <span class="button-text">Proceed...</span>
    <% end %>
  </button>
</div>

app/views/nodes/show.html.erb
<div class="container">
  <br><br>
  <div class="card main-card">
    <br>
    <% @previous_nodes.each do |previous_node| %>
      <div class="sentence-card">
        <p class="lead sentence">
          <%= previous_node.sentence %>
          <span class="signature">-<%= previous_node.signature %></span>
        </p>
        <img class="gif" src="<%= previous_node.gif_url %>">
      </div>
    <% end %>
  </div>
  <% if @previous_nodes.length > 0 %>
    <% if @previous_nodes[-1].next_nodes_ids == nil %>
      <br>
      <%= render "nodes/node_form" %>
    <% end %>
  <% else %>
    <%= render "nodes/node_buttons" %>
  <% end %>

</div>

app/views/stories/_story_form.html.erb
<div class="card add-passage">
  <div class="card-body">
    <h4>Start from scratch.</h4>
    <%= form_for Story.new do |f| %>
      <%#= f.label :sentence, "Keep the story going:" %>
      <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
      <br>
      <%= f.submit "Create", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/stories/index.html.erb
<% @stories.each do |story| %>
  <%= link_to story.title, story_path(story) %>
<% end %>

<%= render "stories/story_form" %>

app/views/stories/show.html.erb
 <div class="stories_show">
  <h1><%= @story.title %></h1>

  <div class="container">
    <br><br>
    <div class="card main-card">
      <br>
      <% @story.nodes.reverse.each do |node| %>
        <div class="sentence-card">
          <p class="lead sentence">
            <%= node.sentence %>
            <span class="signature">-<%= node.signature %></span>
          </p>
          <img class="gif" src="<%= node.gif_url %>">
        </div>
      <% end %>
    </div>
    <br>
      <% if @next_nodes == nil %>
        <%= render "nodes/node_form" %>
      <% else %>
        <%= render "nodes/node_buttons" %>
      <% end %>
  </div>
 </div>